/**
 * Full crawl: Molecule ipNFTs, then Research Hub papers + proposals.
 *
 * From repo root: node crawlers/full-crawl.mjs
 * From crawlers/:  node full-crawl.mjs
 *
 * Crawl-log (Arweave): set AGENT_WALLET in repo-root .env (or the environment) to the same
 * Arweave address as the JWK in Arweave-Cli/.env (WALLET_PATH). Before crawls, the latest
 * on-chain JSON with tag
 * doctype=crawllog is loaded so known molecule folders / researchhub files are skipped.
 * After crawls, merged crawl-log.json is uploaded via node Arweave-Cli/arweaveServiceCLI.js
 * (tags: doctype, Crawl-Date, Content-Type); receipt at crawlers/output/crawl-upload-receipt.json.
 * Pass --no-upload to skip the upload step (local testing).
 *
 * Manifests (papers_manifest.json, proposals/manifest.json) are always regenerated by the
 * Python crawlers; merge still includes them when present on disk so cumulative crawl-log
 * stays consistent.
 */
import { spawnSync } from "node:child_process";
import fsSync from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const crawlers = __dirname;
const repoRoot = path.join(crawlers, "..");

/** Load Claim-extractor/.env into process.env (does not override existing vars). */
function loadRepoRootEnv() {
  const envPath = path.join(repoRoot, ".env");
  if (!fsSync.existsSync(envPath)) return;
  const source = fsSync.readFileSync(envPath, "utf-8");
  for (const line of source.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    if (!key || process.env[key] !== undefined) continue;
    let raw = trimmed.slice(eq + 1).trim();
    if (
      (raw.startsWith('"') && raw.endsWith('"')) ||
      (raw.startsWith("'") && raw.endsWith("'"))
    ) {
      raw = raw.slice(1, -1);
    }
    process.env[key] = raw;
  }
}

loadRepoRootEnv();

const moleculeCwd = path.join(crawlers, "molecule", "crawler");
const researchHubCwd = path.join(crawlers, "research-hub");
const researchHubOut = path.join(crawlers, "output", "researchhub");
const outputDir = path.join(crawlers, "output");
const skipFilePath = path.join(outputDir, ".crawl-skip.json");
const crawlLogPath = path.join(outputDir, "crawl-log.json");
const uploadReceiptPath = path.join(outputDir, "crawl-upload-receipt.json");
const moleculeIpnftsOut = path.join(crawlers, "output", "molecule", "ipnfts");
const arweaveCliDir = path.join(repoRoot, "Arweave-Cli");
const arweaveServiceCli = path.join(arweaveCliDir, "arweaveServiceCLI.js");

const python = process.platform === "win32" ? "python" : "python3";

const ARWEAVE_GQL =
  process.env.ARWEAVE_GRAPHQL_URL ?? "https://arweave.net/graphql";

const GQL_CRAWL_LOG = `
query CrawlLogTxs($owners: [String!]!) {
  transactions(
    owners: $owners
    tags: [{ name: "doctype", values: ["crawllog"] }]
    first: 50
  ) {
    edges {
      node {
        id
        block {
          timestamp
        }
      }
    }
  }
}
`;

/** @returns {{ log: Record<string, unknown> | null, txId: string | null }} */
async function fetchLatestCrawlLog(agentWallet) {
  const body = JSON.stringify({
    query: GQL_CRAWL_LOG,
    variables: { owners: [agentWallet] },
  });
  let res;
  try {
    res = await fetch(ARWEAVE_GQL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body,
    });
  } catch {
    return { log: null, txId: null };
  }
  if (!res.ok) return { log: null, txId: null };
  const parsed = await res.json();
  if (parsed.errors?.length) return { log: null, txId: null };
  const edges = parsed.data?.transactions?.edges ?? [];
  if (edges.length === 0) return { log: null, txId: null };

  let bestId = null;
  let bestTs = -1;
  for (const e of edges) {
    const n = e?.node;
    if (!n?.id) continue;
    const ts = n.block?.timestamp ?? 0;
    if (ts >= bestTs) {
      bestTs = ts;
      bestId = n.id;
    }
  }
  if (!bestId) {
    bestId = edges[0].node.id;
  }

  let dataRes;
  try {
    dataRes = await fetch(`https://arweave.net/${bestId}`);
  } catch {
    return { log: null, txId: null };
  }
  if (!dataRes.ok) return { log: null, txId: null };
  let log;
  try {
    const text = await dataRes.text();
    log = JSON.parse(text);
  } catch {
    return { log: null, txId: null };
  }
  if (!log || typeof log !== "object") return { log: null, txId: null };
  if (!Array.isArray(log.researchhub?.files) || !Array.isArray(log.molecule?.folders)) {
    return { log: null, txId: null };
  }
  return { log, txId: bestId };
}

async function writeCrawlSkipFile(absPath, log) {
  const moleculeFolders = log?.molecule?.folders ?? [];
  const researchhubFiles = log?.researchhub?.files ?? [];
  await fs.mkdir(path.dirname(absPath), { recursive: true });
  await fs.writeFile(
    absPath,
    JSON.stringify({ moleculeFolders, researchhubFiles }, null, 2),
    "utf-8",
  );
}

async function listResearchhubRelativeFiles(rhRoot) {
  const out = [];
  for (const sub of ["papers", "proposals"]) {
    const dir = path.join(rhRoot, sub);
    let names;
    try {
      names = await fs.readdir(dir);
    } catch {
      continue;
    }
    for (const n of names) {
      const full = path.join(dir, n);
      let st;
      try {
        st = await fs.stat(full);
      } catch {
        continue;
      }
      if (st.isFile()) out.push(`${sub}/${n}`.replace(/\\/g, "/"));
    }
  }
  return out.sort();
}

async function listMoleculeTopFolders(ipnftsRoot) {
  let entries;
  try {
    entries = await fs.readdir(ipnftsRoot, { withFileTypes: true });
  } catch {
    return [];
  }
  return entries
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

function parseUploadWebUrl(stdout) {
  const m = stdout.match(
    /File is live at:\s*(https:\/\/arweave\.net\/[A-Za-z0-9_-]+)/,
  );
  return m ? m[1] : null;
}

function txIdFromArweaveNetUrl(webUrl) {
  const prefix = "https://arweave.net/";
  return webUrl.startsWith(prefix) ? webUrl.slice(prefix.length) : null;
}

function mergeCrawlLog(previousLog, diskFiles, diskFolders, previousTxId) {
  const prevFiles = previousLog?.researchhub?.files ?? [];
  const prevFolders = previousLog?.molecule?.folders ?? [];
  const files = [...new Set([...prevFiles, ...diskFiles])].sort();
  const folders = [...new Set([...prevFolders, ...diskFolders])].sort();
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    previousArweaveTxId: previousTxId ?? null,
    researchhub: { files },
    molecule: { folders },
  };
}

const noUpload = process.argv.includes("--no-upload");

const agentWallet = process.env.AGENT_WALLET?.trim();

let previousLog = null;
let previousTxId = null;
if (agentWallet) {
  const r = await fetchLatestCrawlLog(agentWallet);
  previousLog = r.log;
  previousTxId = r.txId;
  console.error(
    previousTxId
      ? `[crawl-log] Loaded previous log from tx ${previousTxId}`
      : "[crawl-log] No previous crawl-log on chain (cold start or fetch failed).",
  );
  await writeCrawlSkipFile(skipFilePath, previousLog ?? {});
} else {
  console.error(
    "[crawl-log] AGENT_WALLET unset — skipping remote log fetch; no incremental skip.",
  );
  await fs.mkdir(outputDir, { recursive: true });
  await writeCrawlSkipFile(skipFilePath, {});
}

const skipArg = skipFilePath;

const steps = [
  {
    label: "molecule: crawl (profiles + data-bundle)",
    cwd: moleculeCwd,
    cmd: "npm",
    args: [
      "run",
      "cli",
      "--",
      "crawl",
      "--output-dir",
      "@crawlers/output/molecule/ipnfts",
      "--competent-only",
      "--crawl-skip-file",
      skipArg,
    ],
    shell: process.platform === "win32",
  },
  {
    label: "research-hub: crawl-for-review.py",
    cwd: researchHubCwd,
    cmd: python,
    args: [
      "crawl-for-review.py",
      "--output-dir",
      researchHubOut,
      "--crawl-skip-file",
      skipArg,
    ],
    shell: false,
  },
];

for (const step of steps) {
  console.error(`\n=== ${step.label} ===\n`);
  const r = spawnSync(step.cmd, step.args, {
    cwd: step.cwd,
    stdio: "inherit",
    env: process.env,
    shell: step.shell,
  });
  if (r.error) {
    console.error(r.error);
    process.exit(1);
  }
  if (r.signal) {
    console.error(`\nStopped: "${step.label}" killed by signal ${r.signal}.`);
    process.exit(1);
  }
  const code = typeof r.status === "number" ? r.status : 1;
  if (code !== 0) {
    console.error(`\nStopped: "${step.label}" exited with ${code}.`);
    process.exit(code);
  }
}

const diskRh = await listResearchhubRelativeFiles(researchHubOut);
const diskMol = await listMoleculeTopFolders(moleculeIpnftsOut);
const merged = mergeCrawlLog(previousLog, diskRh, diskMol, previousTxId);
await fs.mkdir(outputDir, { recursive: true });
await fs.writeFile(crawlLogPath, JSON.stringify(merged, null, 2), "utf-8");
console.error(`\n[crawl-log] Wrote ${crawlLogPath}`);

if (noUpload) {
  console.error("[crawl-log] --no-upload: skipping Arweave upload.");
} else {
  const crawlDate = merged.updatedAt;
  const nodeArgs = [
    arweaveServiceCli,
    crawlLogPath,
    "--tag",
    "doctype=crawllog",
    "--tag",
    `Crawl-Date=${crawlDate}`,
    "--tag",
    "Content-Type=application/json",
  ];
  console.error("\n=== crawl-log: upload to Arweave ===\n");
  const up = spawnSync("node", nodeArgs, {
    cwd: arweaveCliDir,
    encoding: "utf-8",
    env: process.env,
    shell: false,
  });
  if (up.error) {
    console.error(up.error);
    process.exit(1);
  }
  const stdout = up.stdout ?? "";
  const stderr = up.stderr ?? "";
  const webUrl = parseUploadWebUrl(stdout);
  const txId = webUrl ? txIdFromArweaveNetUrl(webUrl) : null;
  const exitCode = typeof up.status === "number" ? up.status : 1;
  const success = webUrl !== null && exitCode === 0;
  await fs.mkdir(path.dirname(uploadReceiptPath), { recursive: true });
  await fs.writeFile(
    uploadReceiptPath,
    `${JSON.stringify(
      {
        success,
        uploaded_file: crawlLogPath,
        tx_id: txId,
        web_url: webUrl,
        cli_stdout: stdout,
        cli_stderr: stderr,
        exit_code: exitCode,
        cli_command: ["node", ...nodeArgs],
      },
      null,
      2,
    )}\n`,
    "utf-8",
  );
  console.error(`[crawl-log] Receipt: ${uploadReceiptPath}`);
  if (!success) {
    console.error(
      `\nStopped: crawl-log upload failed (exit ${exitCode}). See receipt stderr.`,
    );
    process.exit(1);
  }
}

console.error("\n=== full crawl finished ===\n");
